/*
  - layout.tsx
  - template.tsx : 페이지 넘나들 때, 리렌더링/마운트 원할 경우 사용 (layout.tsx와 동시에 존재할 수 없음)
*/
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
